### ISSUE TITLE
Offchain utils -- challenge period calculator

### ISSUE THREAD

**Issue by ZenGround0** [FilOzone/pdp#2]
Challenge period calculator -- @anorth has more context here.  Basically for some parameters users care about we can calculate reasonable challenge parameters.  We should build a tool for calculating this.  Probably this belongs in an online visual tool.  To start with maybe a go-cli program is enough.

**Comment by anorth** [comment]
I think we should write this code in Solidity as well and make it callable as a view method.

**Comment by ZenGround0** [comment]
Since we're enforcing/recording fixed proving period and challenge count parameters in the SimplePDPService I don't think we need this for launch.
