### ISSUE TITLE
PDP Methods should take in extra data

### ISSUE THREAD

**Issue by ZenGround0** [FilOzone/pdp#56]
The PDP Listener interface should allow an extra data param to be threaded through from the caller.  This means we should add extra data params into the main PDP interface to allow caller to talk directly to the listener.  This lets us use the safer, cleaner listener pattern but still allow for protocol extensions in base PDP that allow offchain auth and other extensions.  The canonical example is an application that allows PDP client to fully determine the allowlist of valid cids to be added to proofset.

1. Without extra data: in this case the PDP client must go to the application contract directly and store the valid cids that are allowed to be added to the proofset in the contract state before the PDP SP can call PDP addroots.
2. With extra data: signature is sent to PDP SP who then includes it and passes to listener during addRoots call

**Comment by ZenGround0** [comment]
Note: this is the approach we used for DDO

**Comment by magik6k** [comment]
Makes sense, definitely at least for the non-prove calls
