### ISSUE TITLE
behaviour of `nextProving period` in simplePDP

### ISSUE THREAD

**Issue by irenegia** [FilOzone/pdp#65]
```
if (!provenThisPeriod[proofSetId]) {
            uint256 periodsSkipped = 1;
            if (provingDeadlines[proofSetId] < block.number) {
                periodsSkipped = 1 + ((block.number - provingDeadlines[proofSetId]) / getMaxProvingPeriod());
            }
            emit FaultRecord(FaultType.SKIPPED, periodsSkipped);

```

@ZenGround0, I believe that when `nextProvingPeriod` is called before a proof is received, the DPD service should revert the removals done by the PDPverifier function and do nothing else. All the faults accounting should be done in the pdp service `possesionProven` function

cc @lucaniz

https://github.com/FILCAT/pdp/blob/14fd1c9225471aab4a517abdaf4791c8d9963fd4/contracts/src/SimplePDPService.sol#L169

**Comment by anorth** [comment]
Yes, I think this is the same thing I noted in https://github.com/FILCAT/pdp/pull/63#discussion_r1807935410. The PR was merged "to be reviewed" so I expect this to be fixed up when Zen is back online.

**Comment by anorth** [comment]
I chatted with @irenegia and team about this. They're attempting to avoid a caller being marked faulty potentially unnecessarily (they made a mistake?), before the deadline has elapsed. One possible change would be to disallow this method before the deadline has passed.

This would add a little complexity and reduce freedom. At the moment I don't think it's quite worth it, but it's something to consider.
