### ISSUE TITLE
updating proving deadline

### ISSUE THREAD

**Issue by irenegia** [FilOzone/pdp#66]
https://github.com/FILCAT/pdp/blob/14fd1c9225471aab4a517abdaf4791c8d9963fd4/contracts/src/SimplePDPService.sol#L132C59-L132C78

@ZenGround0 , this is the line that initialise the proving deadline of a proofset, but we can not find where the proving deadline is updated.

cc @lucaniz

**Comment by anorth** [comment]
Yes, I think this is the same thing I noted in https://github.com/FILCAT/pdp/pull/63#discussion_r1807935410. The PR was merged "to be reviewed" so I expect this to be fixed up when Zen is back online.
