### ISSUE TITLE
Change in challengeFinality (value and naming)

### ISSUE THREAD

**Issue by lucaniz** [FilOzone/pdp#81]
Context: when add the first root to a partition, the first challenge epoch is set as current block number number + 1 (i.e. challenge finality = 1).

This means that in the very fist proving step we do not have the challenge window being "respected" (i.e. first challegne does not fall within the last 30 min before the very first deadline).

We propose to take challenge epoch = current block + 2830 (so that any lag between addRoots in PDP.Verifier and the call of RootsAdded in SimplePDPService is taken into account [10 epochs]). This way we should be able to have the challenge epoch within the lat 30 min of the first proving period. (note that we can also get rid of challenge finality here).

As a side effect we'd also solve predictability. 

In terms of naming, we suggest to call it ChallengeDelay rather than challenge finality

https://github.com/FilOzone/pdp/blob/13ca04040b0e5a40a1b5bc8bd4f33fedbf58c614/src/PDPVerifier.sol#L294

**Comment by aarshkshah1992** [comment]
@ZenGround0 

```
As a side effect we'd also solve predictability.
```

Basically, you can't do `addRoots` -> see what the challenge epoch is -> go and re-org the chain if you don't like the challenge -> can do it because challenge finality is 1 when you add the first root.

However, this attack only exists for the first root and so I wouldn't worry too much about it.

**Comment by lucaniz** [comment]
> For example if you wanted a service where you do proving periods half the size then you would be stuck because you couldn't prove during your first proving period.

I understand what you are saying here. Basically if we keep the status quo you'll have a "up to 48h" first window but you'll keep full flexibility no matter how distant two consecutive deadline are set up. 

On the other hand, if you move to what irene and I are proposing, you'd tailor the first window to the current deadline pattern but you'd have a 24h first deadline if you change that pattern, no matter what.

**Comment by lucaniz** [comment]
> Basically, an SP can do addRoots -> see what the challenge epoch is -> go and re-org the chain if you don't like the challenge -> can do it because challenge finality is 1 when you add the first root. However, this attack only exists for the first root and so I wouldn't worry too much about it.

Correct, and also correct this would only apply for the first root.
The mitigation  was actually a side effect of the change we are proposing, not a "primary reason" to introduce it. 
The primary reason was indeed to avoid the "difference" between the very first deadline and all the other ones. But I understand that you are saying this would make a difference anyway if deadline pattern is modified. 

Idk if having it a bit longer than 1 could help, nor if it is problematic to change in the code. Let me think about it while you tell me how bad it is to be changed :)

**Comment by ZenGround0** [comment]
Name is good after clearing up misunderstanding

Setting challengefinality to 150 as in filecoin PoRep gives us needed security.  Including comment for this in #85
